### ISSUE TITLE
Implementation of other neuron types

### ISSUE THREAD

**Issue by 51616** [apple/learning-subspaces#2]
I read the paper and found this approach very interesting. However, I do not see any implementation of other neuron types (e.g., FullyConnected or LSTM).

So, I'm a little curious. Have you guys done any experiment regarding those layers? Would those kind of layers work as well?

Edit1. As I went through the code, I see that only the weights of the conv are being sampled but not the biases. Why is that the case?

**Comment by mitchellnw** [comment]
We have not experimented with other layers, though my guess is that it should still work!

Those convs do not have bias terms, as usually convs do not have biases if they are immediately before batch norms (which do have sampled bias terms).

**Comment by 51616** [comment]
Thank you for the answer :)
