### ISSUE TITLE
Are trained models available ?

### ISSUE THREAD

**Issue by pclucas14** [apple/learning-subspaces#3]
Hi, 

great job on the paper and code :) I was hoping you could share your trained models (esp. on the Imagenet dataset). It would be super appreciated. 

Thanks!
Lucas

**Comment by mitchellnw** [comment]
Hey Lucas, not extremely optimistic but looking into this.

In [another repo for a more recent project](https://github.com/mlfoundations/wise-ft) we do provide [weights](https://drive.google.com/drive/folders/1f56kjpRKPiNSaUxNDtETEDRkbDkZnpCQ) for a subspace of models which, depending on your use case, may be sufficient.

Sorry for the inconvenience and will let you know soon.

**Comment by pclucas14** [comment]
Hi!

thanks for the fast answer :) The model in the other repo looks sufficient. I'll close the issue

**Comment by mitchellnw** [comment]
Ok sweet, please let me know if we can be helpful in any ways!

**Comment by pclucas14** [comment]
Hi, 

how exactly does one read the downloaded checkpoints ? 

I tried 
```
torch.load('zeroshot.pt')
```
and like the `torch_load` as shown [here](https://github.com/mlfoundations/wise-ft/blob/master/src/models/utils.py#L48)
```
with open('zeroshot.pt', 'rb') as f: 
    classifier = pkl.load(f)
```

and I get the same error for both : `ModuleNotFoundError: No module named 'src' `

Thanks

**Comment by mitchellnw** [comment]
I'm stepping out for a sec so may be worth posting this as an issue in the other repo as Gabriel will also be able to help.

My initial guess is that error goes away if you run `export PYTHONPATH=$PWD/src` as it says to do [here](https://github.com/mlfoundations/wise-ft#add-directory-to-pythonpath) ? Still very curious that you get that error when you just do `torch.load` so maybe Gabriel will have other thoughts

**Comment by mitchellnw** [comment]
Gabriel recommends to load via

https://github.com/mlfoundations/wise-ft/blob/master/src/wise_ft.py#L35

**Comment by pclucas14** [comment]
Thanks Mitchell :) I ended up training a model from scratch on TinyImagenet. The repo is super easy to use, so it wasn't too much of a hastle

**Comment by mitchellnw** [comment]
Ok sweet that's great to hear! Apologies for the inconveniences -- the other repo is still not officially released (i.e., we have not updated the arxiv to link to the code), so still ironing out a few bugs.
